name: eagan_public
channels:
 - conda-forge
name: geospatial
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - plotly
    - scipy
  - conda
  - conda:
    - ipykernel 